/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tcu.coletadeprecos.gui;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import tcu.coletadeprecos.model.Empresa;

/**
 *
 * @author x05930906912
 */
public class JFAddColeta extends javax.swing.JFrame {
    
     Empresa empresa = new Empresa();
    /**
     * Creates new form JFInicial
     */
    public JFAddColeta() {
        initComponents();
        
        jText_Item.setText(String.valueOf(empresa.getItem()));
        jButton_Confirmar = new JButton();
        jButton_Finalizar = new JButton();
        jButton_ItemDown = new JButton();
        jButton_ItemUp = new JButton();
        jButton_Limpar = new JButton();
        jButton_QtdDown = new JButton();
        jButton_QtdUp = new JButton();
        jButton_Voltar = new JButton();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_Empresa = new javax.swing.JTextField();
        jLabel_Empresa = new javax.swing.JLabel();
        jLabel_Desc = new javax.swing.JLabel();
        jText_Desc = new javax.swing.JTextField();
        jText_Qtd = new javax.swing.JTextField();
        jLabel_Qtd = new javax.swing.JLabel();
        jText_VlrUnitario = new javax.swing.JTextField();
        jLabel_VlrUnitario = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();
        jText_Total = new javax.swing.JTextField();
        jButton_QtdUp = new javax.swing.JButton();
        jButton_QtdDown = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Confirmar = new javax.swing.JButton();
        jButton_Limpar = new javax.swing.JButton();
        jButton_ItemUp = new javax.swing.JButton();
        jText_Item = new javax.swing.JTextField();
        jButton_ItemDown = new javax.swing.JButton();
        jLabel_Qtd1 = new javax.swing.JLabel();
        jButton_Finalizar = new javax.swing.JButton();
        jButton_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coleta de Preços");
        setBackground(new java.awt.Color(153, 153, 255));

        jText_Empresa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jText_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_EmpresaActionPerformed(evt);
            }
        });

        jLabel_Empresa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Empresa.setText("Nome da empresa");

        jLabel_Desc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Desc.setText("Descrição");

        jText_Desc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jText_Desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_DescActionPerformed(evt);
            }
        });

        jText_Qtd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jText_Qtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_QtdActionPerformed(evt);
            }
        });

        jLabel_Qtd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Qtd.setText("Quantidade");

        jText_VlrUnitario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jText_VlrUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_VlrUnitarioActionPerformed(evt);
            }
        });

        jLabel_VlrUnitario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_VlrUnitario.setText("Valor unitário");

        jLabel_Total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Total.setText("Total parcial");

        jText_Total.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton_QtdUp.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jButton_QtdUp.setText("+");
        jButton_QtdUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QtdUpActionPerformed(evt);
            }
        });

        jButton_QtdDown.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jButton_QtdDown.setText("-");
        jButton_QtdDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QtdDownActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("R$");

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jLabel2.setText("R$");

        jButton_Confirmar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Confirmar.setText("Confirmar");
        jButton_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmarActionPerformed(evt);
            }
        });

        jButton_Limpar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Limpar.setText("Limpar");
        jButton_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimparActionPerformed(evt);
            }
        });

        jButton_ItemUp.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jButton_ItemUp.setText("+");
        jButton_ItemUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ItemUpActionPerformed(evt);
            }
        });

        jText_Item.setEditable(false);
        jText_Item.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jText_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ItemActionPerformed(evt);
            }
        });

        jButton_ItemDown.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        jButton_ItemDown.setText("-");
        jButton_ItemDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ItemDownActionPerformed(evt);
            }
        });

        jLabel_Qtd1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_Qtd1.setText("Item");

        jButton_Finalizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Finalizar.setText("Finalizar");

        jButton_Voltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Voltar.setText("Voltar");
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Qtd1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_VlrUnitario)
                            .addComponent(jLabel_Qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jText_Total))
                                .addComponent(jLabel_Total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jText_VlrUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jText_Empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                                .addComponent(jText_Desc, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_ItemDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_ItemUp))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_QtdDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_Qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_QtdUp)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(jButton_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jText_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Qtd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ItemUp)
                    .addComponent(jButton_ItemDown))
                .addGap(11, 11, 11)
                .addComponent(jLabel_Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel_Qtd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_QtdUp)
                    .addComponent(jButton_QtdDown))
                .addGap(14, 14, 14)
                .addComponent(jLabel_VlrUnitario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_VlrUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Total)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Confirmar)
                    .addComponent(jButton_Limpar)
                    .addComponent(jButton_Finalizar)
                    .addComponent(jButton_Voltar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_EmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_EmpresaActionPerformed

    private void jText_DescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_DescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_DescActionPerformed

    private void jText_QtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_QtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_QtdActionPerformed

    private void jText_VlrUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_VlrUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_VlrUnitarioActionPerformed

    private void jButton_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ConfirmarActionPerformed

    private void jButton_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimparActionPerformed
       int option = JOptionPane.showConfirmDialog(null ,"Tem certeza que deseja limpar todos os campos?","Limpar",JOptionPane.OK_CANCEL_OPTION);
       if (option == 0) {
        jText_Empresa.setText("");
        jText_Desc.setText("");
        jText_Item.setText(String.valueOf((new Empresa().getItem())));
        jText_Desc.setText("");
        jText_VlrUnitario.setText("");
        jText_Total.setText("");
       }
    }//GEN-LAST:event_jButton_LimparActionPerformed

    private void jText_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ItemActionPerformed
        
    }//GEN-LAST:event_jText_ItemActionPerformed

    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    private void jButton_ItemUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ItemUpActionPerformed
        empresa.setItem(empresa.getItem() + 1);
        jText_Item.setText(String.valueOf(empresa.getItem()));
    }//GEN-LAST:event_jButton_ItemUpActionPerformed

    private void jButton_ItemDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ItemDownActionPerformed
        if (empresa.getItem() > 1){
            empresa.setItem(empresa.getItem() - 1);
            jText_Item.setText(String.valueOf(empresa.getItem()));
        }else{
            empresa.setItem(1);
            jText_Item.setText(String.valueOf(empresa.getItem()));
        }
        
    }//GEN-LAST:event_jButton_ItemDownActionPerformed

    private void jButton_QtdDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QtdDownActionPerformed
        if (empresa.getQtd()> 1){
            empresa.setQtd(empresa.getQtd()- 1);
            jText_Qtd.setText(String.valueOf(empresa.getQtd()));
        }else{
            empresa.setQtd(1);
            jText_Qtd.setText(String.valueOf(empresa.getQtd()));
        }
    }//GEN-LAST:event_jButton_QtdDownActionPerformed

    private void jButton_QtdUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QtdUpActionPerformed
        empresa.setQtd(empresa.getQtd() + 1);
        jText_Qtd.setText(String.valueOf(empresa.getQtd()));
    }//GEN-LAST:event_jButton_QtdUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddColeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Confirmar;
    private javax.swing.JButton jButton_Finalizar;
    private javax.swing.JButton jButton_ItemDown;
    private javax.swing.JButton jButton_ItemUp;
    private javax.swing.JButton jButton_Limpar;
    private javax.swing.JButton jButton_QtdDown;
    private javax.swing.JButton jButton_QtdUp;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Desc;
    private javax.swing.JLabel jLabel_Empresa;
    private javax.swing.JLabel jLabel_Qtd;
    private javax.swing.JLabel jLabel_Qtd1;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JLabel jLabel_VlrUnitario;
    private javax.swing.JTextField jText_Desc;
    private javax.swing.JTextField jText_Empresa;
    private javax.swing.JTextField jText_Item;
    private javax.swing.JTextField jText_Qtd;
    private javax.swing.JTextField jText_Total;
    private javax.swing.JTextField jText_VlrUnitario;
    // End of variables declaration//GEN-END:variables
}
